
SRC+=Arduino.cpp rtc_setup.cpp usart_setup.cpp spi_setup.cpp ring.cpp systick_setup.cpp
SRC+=uprintf.cpp

VPATH+=$(HOME)/teensy/LibStm/LeoStm
VPATH+=$(HOME)/teensy/util
CPPFLAGS+=-I$(HOME)/teensy/LibStm/LeoStm
CPPFLAGS+=-I$(HOME)/teensy/util

TAGS+=$(HOME)/teensy/LibStm/LeoStm
TAGS+=$(HOME)/teensy/util
