
font_text:font_04x06.cpp font_05x08.cpp font_05x12.cpp font_06x08.cpp font_06x10.cpp font_07x12.cpp font_08x08.cpp font_08x12.cpp font_08x14.cpp font_10x16.cpp font_12x16.cpp font_12x20.cpp font_16x26.cpp font_text.cpp
	g++ -ofont_text font_04x06.cpp font_05x08.cpp font_05x12.cpp font_06x08.cpp font_06x10.cpp font_07x12.cpp font_08x08.cpp font_08x12.cpp font_08x14.cpp font_10x16.cpp font_12x16.cpp font_12x20.cpp font_16x26.cpp font_text.cpp
