# cpu =  cortex-m4
# arch = armv7e-m
#
# path dell'ambiente di sviluppo
ARDUINO=/home/leo/teensy/arduino
TEENSY=$(ARDUINO)/hardware/teensy/cores/teensy3

# path dei $(LIB_SRC)
VPATH=$(TEENSY)

# TIME_T serve per inizializzare il RTC ad una data/ora piu' o meno esatta
CFLAGS=-Os -Wall \
	-ffunction-sections -fdata-sections \
	-mcpu=cortex-m4 \
	-mfloat-abi=soft \
	-mthumb \
	-MMD \
	-DF_CPU=96000000 -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 \
	-D__MK20DX256__ -DTEENSYDUINO=118 \
	-DTIME_T=1412425835 -DUSB_SERIAL \
	-DLAYOUT_US_ENGLISH \
	-I $(TEENSY)

CXXFLAGS = $(CFLAGS) \
	-fno-rtti -felide-constructors -std=gnu++0x -fno-exceptions 

CC=arm-none-eabi-gcc
CXX=arm-none-eabi-g++
AR=arm-none-eabi-ar

SRC=\
	Blink.cpp \
	io.cpp

LIB_SRC= \
	analog.c \
	eeprom.c \
	keylayouts.c \
	math_helper.c \
	nonstd.c \
	pins_teensy.c \
	serial1.c \
	serial2.c \
	serial3.c \
	touch.c \
	usb_desc.c \
	usb_dev.c \
	usb_joystick.c \
	usb_keyboard.c \
	usb_mem.c \
	usb_midi.c \
	usb_mouse.c \
	usb_rawhid.c \
	usb_seremu.c \
	usb_serial.c \
	yield.c \
	AudioStream.cpp \
	avr_emulation.cpp \
	HardwareSerial1.cpp \
	HardwareSerial2.cpp \
	HardwareSerial3.cpp \
	IntervalTimer.cpp \
	IPAddress.cpp \
	main.cpp \
	new.cpp \
	Print.cpp \
	Stream.cpp \
	Tone.cpp \
	usb_flightsim.cpp \
	usb_inst.cpp \
	WMath.cpp \
	WString.cpp


# si usa := per evitare la ricursione infinita che si avrebbe con =
LIB_OBJ:=$(patsubst %.cpp,%.o,$(LIB_SRC))
LIB_OBJ:=$(patsubst %.c,%.o,$(LIB_OBJ))
LIB_OBJ:=$(patsubst %.o,obj/%.o,$(LIB_OBJ))

OBJ:=$(patsubst %.cpp,%.o,$(SRC))
OBJ:=$(patsubst %.c,%.o,$(OBJ))
OBJ:=$(patsubst %.o,obj/%.o,$(OBJ))

obj/%.o : %.cpp
	@echo $(notdir $<)
	@$(CXX) -c $(CXXFLAGS) $< -o $@
obj/%.o : %.c
	@echo $(notdir $<)
	@$(CC) -c $(CFLAGS) $< -o $@

%.s : %.cpp
	$(CXX) -S -c $(CXXFLAGS) $< -o $@
%.s : %.c
	$(CC) -S -c $(CFLAGS) $< -o $@

TARGET=Blink

$(TARGET).elf $(TARGET).eep $(TARGET).hex : $(OBJ) obj/mk20dx128.o libTeensy.a
	@echo link $(TARGET)
	$(CC) -Os -Wl,--gc-sections -Wl,-Map=$(TARGET).map -Wl,-v \
		-mcpu=cortex-m4 -mthumb \
		-mfloat-abi=soft \
		-T $(TEENSY)/mk20dx256.ld \
		-o $(TARGET).elf \
		-L. \
		obj/mk20dx128.o $(OBJ) -lTeensy -lm
	@arm-none-eabi-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load \
		--no-change-warnings --change-section-lma .eeprom=0 \
		$(TARGET).elf $(TARGET).eep 
	@arm-none-eabi-strip -g  $(TARGET).elf
	@arm-none-eabi-objcopy -O ihex -R .eeprom $(TARGET).elf $(TARGET).hex 
	@arm-none-eabi-objdump -S -D $(TARGET).elf > $(TARGET).dis 
	@arm-none-eabi-size  $(TARGET).elf

obj/mk20dx128.o : | obj
$(LIB_OBJ): | obj
$(OBJ): | obj

obj :
	mkdir -p obj

libTeensy.a : $(LIB_OBJ)
	@echo $(notdir $<)
	@rm -f $@
	@$(AR) -cvq $@ $^

upload : $(TARGET).hex teensy_loader_cli
	teensy_loader_cli -mmcu=mk20dx256 -v -w $(TARGET).hex


-include $(LIB_OBJ:.o=.d)
-include $(OBJ:.o=.d)

clean : 
	-rm -f $(TARGET).elf
	-rm -f $(TARGET).eep
	-rm -f $(TARGET).hex
	-rm -f $(TARGET).map
	-rm -f $(TARGET).dis
	-rm -f $(TARGET).d
	-rm -f $(TARGET).s
	-rm -f libTeensy.a
	-rm -rf obj
	-rm -f teensy_loader_cli 

ifeq ($(shell uname),Linux)
DD=-DUSE_LIBUSB=1
LL=-lusb
else
DD=-DUSE_WIN32=1
LL=-lsetupapi -lhid
endif

teensy_loader_cli : teensy_loader_cli.c
	gcc $(DD) teensy_loader_cli.c $(LL) -o teensy_loader_cli
